---
title: "EDA_Hu_Zhongyang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

intialize data

```{r }
final_fire=read.csv('final_wildfire.csv')
summary_nature=read.csv('summary_nature.csv')
summary_peoplecaused=read.csv('summary_peoplecaused.csv')
colnames(summary_nature)[4]='temperature'
colnames(summary_nature)[5]='soilmoisture'
colnames(summary_nature)[6]='rainfall'
colnames(summary_nature)[7]='nfire'
colnames(summary_peoplecaused)[4]='temperature'
colnames(summary_peoplecaused)[5]='soilmoisture'
colnames(summary_peoplecaused)[6]='rainfall'
colnames(summary_peoplecaused)[7]='nfire'
summary_peoplecaused$Year=as.factor(summary_peoplecaused$Year)

summary_peoplecaused$month=as.factor(summary_peoplecaused$month)
summary_nature$Year=as.factor(summary_nature$Year)

summary_nature$month=as.factor(summary_nature$month)
```

## Including Plots

plot the year trend

```{r , results='markup'}
library(ggplot2)

temp_plot=aggregate(nfire~Year,summary_nature,sum)

temp_plot2=aggregate(nfire~Year,summary_peoplecaused,sum)

ggplot() +geom_point(data=temp_plot, aes(x=Year, y=nfire), colour='blue') + geom_point(data=temp_plot2, aes(x=Year, y=nfire),colour='red')+labs(title='Number of Fires Each Year (red for people caused fire bule for other reasons)',y='Number of Fires')



```


```{r, results='markup' }
library(ggpubr)
ggplot(summary_peoplecaused, mapping=aes(x=Year,y=nfire)) + geom_boxplot()+ggtitle('box-plot of number of people-caused fires for different years')+ylab('Number of Fires')

ggplot(summary_peoplecaused, mapping=aes(x=month,y=nfire)) + geom_boxplot()+ggtitle('box-plot of number of people-caused fires for different months')+ylab('Number of Fires')
ggplot(summary_nature, mapping=aes(x=Year,y=nfire)) + geom_boxplot()+ggtitle('box-plot of number of fires caused by other reasons for different years')+ylab('Number of Fires')

ggplot(summary_nature, mapping=aes(x=month,y=nfire)) + geom_boxplot()+ggtitle('box-plot of number of fires caused by other reasons for different months')+ylab('Number of Fires')

```
```{r}
ggplot(summary_peoplecaused, mapping=aes(x=Year,y=temperature)) + geom_boxplot()+ggtitle('box-plot of temperature for different years')+ylab('temperature')

ggplot(summary_peoplecaused, mapping=aes(x=month,y=temperature)) + geom_boxplot()+ggtitle('box-plot of temperature for different months')+ylab('temperature')
ggplot(summary_nature, mapping=aes(x=Year,y=soilmoisture)) + geom_boxplot()+ggtitle('box-plot of soil moisture for different years')+ylab('soil moisture')

ggplot(summary_nature, mapping=aes(x=month,y=soilmoisture)) + geom_boxplot()+ggtitle('box-plot of soil moisture for different months')+ylab('soil moisture')
ggplot(summary_nature, mapping=aes(x=Year,y=rainfall)) + geom_boxplot()+ggtitle('box-plot of rainfall for different years')+ylab('average daily rainfall')

ggplot(summary_nature, mapping=aes(x=month,y=rainfall)) + geom_boxplot()+ggtitle('box-plot of rainfall for different months')+ylab('average daily rainfall')

```
```{r}
summary(aov(nfire~Year,summary_peoplecaused))
summary(aov(nfire~month,summary_peoplecaused))
summary(aov(nfire~Year,summary_nature))
summary(aov(nfire~month,summary_nature))
summary(aov(temperature~Year,summary_peoplecaused))
summary(aov(temperature~month,summary_peoplecaused))
summary(aov(soilmoisture~Year,summary_nature))
summary(aov(soilmoisture~month,summary_nature))
summary(aov(rainfall~Year,summary_nature))
summary(aov(rainfall~month,summary_nature))
```
```{r}
library(stringr)
temp=str_remove(summary_nature$Budget,"[$]")
temp=str_remove_all(temp,"[,]")
summary_nature$Budget=as.numeric(temp)
temp=str_remove(summary_peoplecaused$Budget,"[$]")
temp=str_remove_all(temp,"[,]")
summary_peoplecaused$Budget=as.numeric(temp)
cor_nature=cor(summary_nature[c(4:9)])

library(corrplot)
corrplot(cor_nature,method='number')
cor_people=cor(summary_peoplecaused[c(4:9)])


corrplot(cor_people,method='number')
summary_nature$total=summary_nature$n+summary_peoplecaused$n
cor_total=cor(summary_nature[c(4,5,6,8,9,10)])


corrplot(cor_total,method='number',type = 'lower', diag = TRUE)
```


create model for nature reason

```{r}

model1=lm(total~temperature,data=summary_nature)
summary(model1)

model2=lm(total~temperature+soilmoisture,data=summary_nature)

summary(model2)
model3=lm(total~temperature+soilmoisture+rainfall,data=summary_nature)
summary(model3)

library(car)
vif(model3)
vif(model2)
model4=lm(total~soilmoisture,data=summary_nature)

summary(model4)

residualPlot(model2)

model5=lm(log(total)~temperature+soilmoisture,data=summary_nature)
residualPlot(model5)
plot(model5)
summary(model5)
vif(model5)
```