---
title: "DTree"
author: "Adarsh Kotla"
date: "4/29/2022"
output: html_document
---

## R Markdown
```{r pressure, echo=FALSE}
install.packages("rpart.plot")
```

```{r pressure, echo=FALSE}
#install.packages("caret")
library(rpart)
library(rpart.plot)
library(caret)
library(tidyverse)
```

```{r pressure, echo=FALSE}
myvars <- c("v1", "v2", "v3")
newdata <- mydata[myvars]
```

```{r pressure, echo=FALSE}
create_train_test(df, size = 0.8, train = TRUE)

create_train_test <- function(data, size = 0.8, train = TRUE) {
    n_row = nrow(data)
    total_row = size * n_row
    train_sample < - 1: total_row
    if (train == TRUE) {
        return (data[train_sample, ])
    } else {
        return (data[-train_sample, ])
    }
}
```

```{r pressure, echo=FALSE}
data_train <- create_train_test(mdb, 0.8, train = TRUE)
data_test <- create_train_test(mdb, 0.8, train = FALSE)
data_test$FIRE_SIZE_CLASS = as.factor(data_test$FIRE_SIZE_CLASS)
```

```{r pressure, echo=FALSE}
# specifying the CV technique which will be passed into the train() function later and number parameter is the "k" in K-fold cross validation
train_control = trainControl(method = "cv", number = 5, search = "grid")

## Customsing the tuning grid (ridge regression has alpha = 0)
multi_classification_Tree_Grid =  expand.grid(maxdepth = c(1,3,5,7,9,10,11))

set.seed(50)

# training a Regression model while tuning parameters (Method = "rpart")
model = train(FIRE_SIZE_CLASS~., data = data_train, method = "rpart2", trControl = train_control, tuneGrid = multi_classification_Tree_Grid)

# summarising the results
print(model)
```

```{r pressure, echo=FALSE}
#use model to make predictions on test data
pred_y = predict(model, data_test)
```

```{r pressure, echo=FALSE}
# confusion Matrix
confusionMatrix(data = pred_y, data_test$FIRE_SIZE_CLASS)
```
#############################################################
```{r pressure, echo=FALSE} 
#predicting only fire classes A and B.
```

```{r pressure, echo=FALSE}
fit <- rpart(FIRE_SIZE_CLASS~., data = data_train, method = 'class')
rpart.plot(fit, extra = 106)
```

```{r pressure, echo=FALSE}
#Prediction
predict_unseen <-predict(fit, data_test, type = 'class')
```

```{r pressure, echo=FALSE}
table_mat <- table(data_test$FIRE_SIZE_CLASS, predict_unseen)
table_mat
```

```{r pressure, echo=FALSE}
#accuracy test
accuracy_Test <- sum(diag(table_mat)) / sum(table_mat)
print(paste('Accuracy for test', accuracy_Test))
```

```{r pressure, echo=FALSE}
#Tune parameters
accuracy_tune <- function(fit) {
    predict_unseen <- predict(fit, data_test, type = 'class')
    table_mat <- table(data_test$FIRE_SIZE_CLASS, predict_unseen)
    accuracy_Test <- sum(diag(table_mat)) / sum(table_mat)
    accuracy_Test
}

control <- rpart.control(minsplit = 4,
    minbucket = round(5 / 3),
    maxdepth = 3,
    cp = 0)
tune_fit <- rpart(FIRE_SIZE_CLASS~., data = data_train, method = 'class', control = control)
accuracy_tune(tune_fit)

```

```{r pressure, echo=FALSE}
# confusion Matrix
confusionMatrix(data = predict_unseen, data_test$FIRE_SIZE_CLASS)
```

```{r pressure, echo=FALSE}
#Prediction 2 after tuning
predict_unseen2 <-predict(tune_fit, data_test, type = 'class')
```

```{r pressure, echo=FALSE}
# confusion Matrix
confusionMatrix(data = predict_unseen2, data_test$FIRE_SIZE_CLASS)
```

```{r pressure, echo=FALSE}
```
